// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ValReadRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValReadRequest) Reset()         { *m = ValReadRequest{} }
func (m *ValReadRequest) String() string { return proto.CompactTextString(m) }
func (*ValReadRequest) ProtoMessage()    {}
func (*ValReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *ValReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValReadRequest.Unmarshal(m, b)
}
func (m *ValReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValReadRequest.Marshal(b, m, deterministic)
}
func (m *ValReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValReadRequest.Merge(m, src)
}
func (m *ValReadRequest) XXX_Size() int {
	return xxx_messageInfo_ValReadRequest.Size(m)
}
func (m *ValReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValReadRequest proto.InternalMessageInfo

func (m *ValReadRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ValReadReply struct {
	Val                  string   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValReadReply) Reset()         { *m = ValReadReply{} }
func (m *ValReadReply) String() string { return proto.CompactTextString(m) }
func (*ValReadReply) ProtoMessage()    {}
func (*ValReadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3}
}

func (m *ValReadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValReadReply.Unmarshal(m, b)
}
func (m *ValReadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValReadReply.Marshal(b, m, deterministic)
}
func (m *ValReadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValReadReply.Merge(m, src)
}
func (m *ValReadReply) XXX_Size() int {
	return xxx_messageInfo_ValReadReply.Size(m)
}
func (m *ValReadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ValReadReply.DiscardUnknown(m)
}

var xxx_messageInfo_ValReadReply proto.InternalMessageInfo

func (m *ValReadReply) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type ValWriteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  string   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValWriteRequest) Reset()         { *m = ValWriteRequest{} }
func (m *ValWriteRequest) String() string { return proto.CompactTextString(m) }
func (*ValWriteRequest) ProtoMessage()    {}
func (*ValWriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{4}
}

func (m *ValWriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValWriteRequest.Unmarshal(m, b)
}
func (m *ValWriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValWriteRequest.Marshal(b, m, deterministic)
}
func (m *ValWriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValWriteRequest.Merge(m, src)
}
func (m *ValWriteRequest) XXX_Size() int {
	return xxx_messageInfo_ValWriteRequest.Size(m)
}
func (m *ValWriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValWriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValWriteRequest proto.InternalMessageInfo

func (m *ValWriteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ValWriteRequest) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type ValWriteReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValWriteReply) Reset()         { *m = ValWriteReply{} }
func (m *ValWriteReply) String() string { return proto.CompactTextString(m) }
func (*ValWriteReply) ProtoMessage()    {}
func (*ValWriteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{5}
}

func (m *ValWriteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValWriteReply.Unmarshal(m, b)
}
func (m *ValWriteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValWriteReply.Marshal(b, m, deterministic)
}
func (m *ValWriteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValWriteReply.Merge(m, src)
}
func (m *ValWriteReply) XXX_Size() int {
	return xxx_messageInfo_ValWriteReply.Size(m)
}
func (m *ValWriteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ValWriteReply.DiscardUnknown(m)
}

var xxx_messageInfo_ValWriteReply proto.InternalMessageInfo

func (m *ValWriteReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*ValReadRequest)(nil), "helloworld.ValReadRequest")
	proto.RegisterType((*ValReadReply)(nil), "helloworld.ValReadReply")
	proto.RegisterType((*ValWriteRequest)(nil), "helloworld.ValWriteRequest")
	proto.RegisterType((*ValWriteReply)(nil), "helloworld.ValWriteReply")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4f, 0xbb, 0x40,
	0x10, 0xc5, 0xff, 0xb4, 0xff, 0x50, 0x9d, 0xb4, 0x96, 0xec, 0xc1, 0x20, 0xbd, 0x34, 0x7b, 0x30,
	0x7a, 0x21, 0x46, 0xe3, 0xd5, 0x28, 0x1e, 0xea, 0xb1, 0xa1, 0x09, 0x3d, 0x8f, 0x76, 0x82, 0xc4,
	0xa1, 0xe0, 0x82, 0x55, 0xbe, 0x87, 0x1f, 0xd8, 0x40, 0xbb, 0xb2, 0x1a, 0xf4, 0xe0, 0x6d, 0x66,
	0xe7, 0xf7, 0x5e, 0x66, 0x5f, 0x06, 0x9c, 0x47, 0x62, 0xce, 0x5e, 0x33, 0xc5, 0x2b, 0x3f, 0x57,
	0x59, 0x99, 0x09, 0x68, 0x5f, 0xa4, 0x84, 0xe1, 0x5d, 0xdd, 0x85, 0xf4, 0xfc, 0x42, 0x45, 0x29,
	0x04, 0xfc, 0x5f, 0x63, 0x4a, 0xae, 0x35, 0xb5, 0x4e, 0xf6, 0xc3, 0xa6, 0x96, 0xc7, 0x00, 0x3b,
	0x26, 0xe7, 0x4a, 0xb8, 0x30, 0x48, 0xa9, 0x28, 0x30, 0xd6, 0x90, 0x6e, 0xa5, 0x84, 0x83, 0x08,
	0x39, 0x24, 0x5c, 0x69, 0x37, 0x07, 0xfa, 0x4f, 0x54, 0xed, 0xb8, 0xba, 0x94, 0x53, 0x18, 0x7e,
	0x32, 0xb5, 0x9b, 0x03, 0xfd, 0x0d, 0xb2, 0x26, 0x36, 0xc8, 0xf2, 0x12, 0xc6, 0x11, 0xf2, 0x52,
	0x25, 0x25, 0xfd, 0x68, 0xa3, 0x65, 0xbd, 0x56, 0x76, 0x0a, 0xa3, 0x56, 0xf6, 0xeb, 0x9e, 0xe7,
	0xef, 0x3d, 0x18, 0xcc, 0x14, 0x51, 0x49, 0x4a, 0x5c, 0xc1, 0xde, 0x02, 0xab, 0xe6, 0x7b, 0xc2,
	0xf5, 0x8d, 0xa8, 0xcc, 0x54, 0xbc, 0xc3, 0x8e, 0x49, 0xce, 0x95, 0xfc, 0x27, 0x6e, 0x61, 0xa4,
	0xf5, 0x37, 0x31, 0x26, 0xeb, 0x3f, 0x99, 0x5c, 0x83, 0x3d, 0xa3, 0x32, 0x42, 0x16, 0x9e, 0xc9,
	0x7c, 0x0d, 0xd3, 0x73, 0x3b, 0x67, 0x5b, 0x87, 0x00, 0xec, 0xc5, 0xd6, 0x61, 0xf2, 0x8d, 0x32,
	0x83, 0xf4, 0x8e, 0xba, 0x87, 0x8d, 0x47, 0x70, 0x06, 0x93, 0x24, 0xf3, 0x63, 0x95, 0x3f, 0xf8,
	0xf4, 0x86, 0x69, 0xce, 0x54, 0x18, 0x78, 0x30, 0x6e, 0x56, 0x5e, 0xd6, 0xf5, 0xbc, 0x3e, 0xa3,
	0xb9, 0x75, 0x6f, 0x37, 0xf7, 0x74, 0xf1, 0x11, 0x00, 0x00, 0xff, 0xff, 0x70, 0x62, 0x97, 0xbe,
	0x63, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	GetVal(ctx context.Context, in *ValReadRequest, opts ...grpc.CallOption) (*ValReadReply, error)
	SetVal(ctx context.Context, in *ValWriteRequest, opts ...grpc.CallOption) (*ValWriteReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHelloAgain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetVal(ctx context.Context, in *ValReadRequest, opts ...grpc.CallOption) (*ValReadReply, error) {
	out := new(ValReadReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/GetVal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SetVal(ctx context.Context, in *ValWriteRequest, opts ...grpc.CallOption) (*ValWriteReply, error) {
	out := new(ValWriteReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SetVal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHelloAgain(context.Context, *HelloRequest) (*HelloReply, error)
	GetVal(context.Context, *ValReadRequest) (*ValReadReply, error)
	SetVal(context.Context, *ValWriteRequest) (*ValWriteReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedGreeterServer) SayHelloAgain(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloAgain not implemented")
}
func (*UnimplementedGreeterServer) GetVal(ctx context.Context, req *ValReadRequest) (*ValReadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVal not implemented")
}
func (*UnimplementedGreeterServer) SetVal(ctx context.Context, req *ValWriteRequest) (*ValWriteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVal not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHelloAgain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHelloAgain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHelloAgain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHelloAgain(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetVal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetVal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/GetVal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetVal(ctx, req.(*ValReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SetVal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SetVal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SetVal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SetVal(ctx, req.(*ValWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayHelloAgain",
			Handler:    _Greeter_SayHelloAgain_Handler,
		},
		{
			MethodName: "GetVal",
			Handler:    _Greeter_GetVal_Handler,
		},
		{
			MethodName: "SetVal",
			Handler:    _Greeter_SetVal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
